site_name: yii2-workflow User Guide
pages:
    - 'Introduction': 'index.md'
    - 'Overview': 'overview.md'
    - Concept:
        - 'Basics': 'concept-overview.md'
        - 'Events': 'concept-events.md'
        - 'Source': 'concept-source.md'
        - 'Validation': 'concept-validation.md'
    - Focus:
      - 'Defining a workflow' : workflow-creation.md
      - 'The source file compoent' : source-file.md
      - 'Upgrade from 1.x' : upgrade.md
    - Cookbook: 'special-cookbook.md'
theme: yeti
