site_name: yii2-workflow User Guide
pages:
    - 'Introduction': 'index.md'
    - 'Overview': 'overview.md'
    - Concept:
        - 'Presentation': 'concept-overview.md'
        - 'Events': 'concept-events.md'
        - 'Source': 'concept-source.md'
        - 'Validation': 'concept-validation.md'
    - Usage:
        - 'The source file compoent' : source-file.md
        - 'Creating a workflow' : workflow-creation.md
    - Cookbook: 'special-cookbook.md'
theme: yeti
